name: GitHub Organization User Activity Report
on: [push]
jobs:
  Explore-GitHub-Actions:
    environment: All
    runs-on: ubuntu-latest
    steps:
      - name: Analyze User Activity
        id: analyze_user_activity
        uses: peter-murray/inactive-users-action@v1
        with:
          token: ${{ secrets.ZZZZ }}
          organization: ClarabridgeInc
          activity_days: 180
      - name: Save User Activity Report
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            ${{ steps.analyze_user_activity.outputs.report_csv }}