name: GitHub Organization User Activity Report
on: [push]
jobs:
  build:
    environment: All
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Organization User Activity Report
        uses: peter-murray/inactive-users-action@v1
        env:
          token: ${{ secrets.ORGANIZATION_AND_REPO_ACCESS_TOKEN }}
          organization: BarysDrahunou