name: GitHub Organization User Activity Report
on: [push]
jobs:
  Explore-GitHub-Actions:
    environment: All
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Organization User Activity Report
        uses: peter-murray/inactive-users-action@v1
        with:
          token: ${{ secrets.ZZZZ }}
          organization: BarysDrahunou
          activity_days: 180