name: GitHub Organization User Activity Report
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Organization User Activity Report
        uses: peter-murray/inactive-users-action@v1
        with:
          token: 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
          organization: BarysDrahunou