name: GitHub Organization User Activity Report
on: [push]
jobs:
  Explore-GitHub-Actions:
    steps:
      - name: GitHub Organization User Activity Report
        uses: peter-murray/inactive-users-action@v1
